# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8070
    servlet:
        context-path: /rabbitmq

spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    freemarker:
      suffix: .html
    rabbitmq:
      host: 39.97.182.195
      port: 20190
      username: admin
      password: admin
      virtual-host: buff_vhost
      template:
            # 使用return-callback时必须设置mandatory为true
        mandatory: true
          # 消息发送到交换机确认机制,是否确认回调
      publisher-confirms: true
          # 消息发送到交换机确认机制，是否返回回调
      publisher-returns: true
      listener:
        simple:
          acknowledge-mode: manual #设置确认模式手工确认
          concurrency: 3 #消费者最小数量
          max-concurrency: 10 # 消费者最大数量